### ISSUE TITLE
🌟User's identity

### ISSUE THREAD

**Issue by AliceETRX** [AdrKacz/super-duper-guacamole#122]
# Is your feature request related to a problem? Please describe
Si nous voulons que les utilisateurs se rencontrent en vrai, nous devons faire en sorte qu'ils sachent avec qui, et potentiellement de les rassurer aussi car cela peut être inquiétant de rencontrer quelqu'un dont on ne sait rien.

# Describe the solution you'd like
Ajout d'un bouton pour révéler son identité : photo et nom. La photo remplace l'avatar robot.
L'utilisateur pourrait donc avoir le choix à un moment de la conversation de révéler son identité aux autres membres du groupe.
Celui ci pourrait donc créer un profil.

**Comment by AdrKacz** [comment]
Done.
