### ISSUE TITLE
🌟 Créer un groupe "random"

### ISSUE THREAD

**Issue by AliceETRX** [AdrKacz/super-duper-guacamole#134]
# Is your feature request related to a problem? Please describe
Pour les personnes qui souhaitent parler à n'importe qui, peu importe la ville dans laquelle ils sont, il s'agit de créer un choix autre que la ville.

# Describe the solution you'd like
Les utilisateurs peuvent choisir soit une ville, soit, la possibilité d'être mis dans un groupe de personnes venant de partout "dans le monde" : un groupe "random". Si elles choisissent l'option "random", elles ne sont mises qu'avec des personnes ayant choisis cette même option.

# Describe alternatives you've considered
Trouver un nom pour cette option

# Additional context
Ces personnes là doivent être misent ensemble et non pas éparpillées dans des groupes avec d'autres personnes qui, elles, ont choisie une ville en particulier pour se rencontrer. Car cela serait embêtant d'avoir un "outsider" dans le groupe pour les utilisateurs qui veulent se rencontrer d'avoir un "outsider" dans le groupe.

**Comment by AdrKacz** [comment]
Va être résolu avec #208
