### ISSUE TITLE
🌟 Possibilité de choisir le lieu le plus actif

### ISSUE THREAD

**Issue by AliceETRX** [AdrKacz/super-duper-guacamole#135]
# Is your feature request related to a problem? Please describe
Dans le but de mettre le plus de personne ensemble et ne pas se retrouver avec des groupes vides et continuer d'avoir des interactions avec les utilisateurs, ceux ci peuvent avoir le choix de choisir non pas leur ville mais la ville la plus active.

# Describe the solution you'd like
Ainsi, 3 possibilités :
- Choisir sa ville (ou celle que l'on veut du moins)
- Choisir le groupe "random" pour chatter avec des personnes venant de partout dans le monde
- Choisir le lieu le plus actif du moment

**Comment by mbeaufre** [comment]
Je commente pour faire remonter cette idée: Avec l'ajout de la localisation, on peut par exemple être situé à Villeurbanne mais vouloir être à Lyon pour pouvoir planifier sa soirée ? 
Cela revient un peu à permettre à l'utilisateur de choisir sa localisation pour qu'il s'organise au mieux en fonction de ce qu'il cherche.

**Comment by AdrKacz** [comment]
L'utilisateur choisi sa ville, donc pas trop de problème avec a pour le moment, on verra quand on aura une loc automatique. Je ferme pour le moment.
