### ISSUE TITLE
Faire un site web + nom de domaine 💻

### ISSUE THREAD

**Issue by AliceETRX** [AdrKacz/super-duper-guacamole#142]
- Via quel outil créer le site web ?
- Définir un nom de domaine pour notre site
- Voir les coûts pour nom de domaine et hosting site web

**Comment by AliceETRX** [comment]
- Utilisation de Wordpress.com en ce moment
- Besoin de définir un nom de domaine et de l'acheter
- Besoin de télécharger Wordpress.org *(mieux ?)*

**Comment by AliceETRX** [comment]
Nom domaine et site web : https://www.awa-chat.me
(Utilisation de wordpress.org)

**Reste à faire:**
- finir la page **politique de confidentialité** (utilisation et conservation des données)
- est-ce qu'on met un **formulaire** sur la page contact ou est-ce qu'on laisse juste l'adresse mail où l'on peut nous contacter ? Perso, je suis d'avis à mettre un form, ça fait plus pro ET on va pouvoir gérer ça sur la plateforme wordpress avec des stats etc

**Comment by AdrKacz** [comment]
Je pense qu'on peut mettre un formulaire, ça permet à ceux qui n'arrivent pas à ouvrir le lien de quand meme pouvoir envoyer un feed-back.

Il faut aussi qu'on _link_ tout nos autre moyens de communication. Donc si on met un formulaire, on garde quand même l'email (si quelqu'un veut nous envoyer un e-mail plutôt que remplir le formulaire) et on affiche le lien vers le Chat Messenger (si quelqu'un est plus à l'aise de dialoguer avec nous via Messenger)

Ça te semble bien ? 😁

**Comment by AliceETRX** [comment]
Page de confidentialité faite : https://www.awa-chat.me/politique-de-confidentialite/

Page de contact avec formulaire (**vérifié et testé**, il marche même sans avoir besoin de mettre son email): https://www.awa-chat.me/contact/

**Reste à faire**
- ajouter messenger
- ajouter page de téléchargement lien direct vers les stores (je me comprends)

**Comment by AdrKacz** [comment]
C'est done (voir [awa-chat.me](awa-chat.me) et [download.awa-chat.me](download.awa-chat.me))
