### ISSUE TITLE
🐛 Contactez-nous - email link

### ISSUE THREAD

**Issue by mbeaufre** [AdrKacz/super-duper-guacamole#171]
# Describe the bug
When clicking on awachat.app@gmail.com in the contact page, we would expect the app to open a mailbox. However, it fails to do so on the device described below (Android).
However the link is working as expected (open a mail to write) on an iPhone 8.
 My guess is: 
- When clicking on this link, we try to open the mail app, which is different between iOS and Android. This is where lies the error.

# To Reproduce
1. Go to 'Contactez-Nous' tab
2. Click on 'awachat.app@gmail.com'
3. See error

# Expected behavior
The app should open a mail in Gmail with 'awachat.app@gmail.com' as the recipient.

# Screenshots
![291511902_1266042664165485_2641444479205649896_n](https://user-images.githubusercontent.com/79444086/177546278-f811ae0e-9b32-4b90-b1a4-b6280466ecbd.jpg)
![292267073_392168606095264_7318346288994125113_n](https://user-images.githubusercontent.com/79444086/177546292-85d0aec8-9167-4546-8d3b-42fd0e76179b.jpg)

# Smartphone (please complete the following information)
 - Device: Oppo X3 Lite
 - OS: Android 12

**Comment by AliceETRX** [comment]
J'ai ajouter un formulaire sur la page contact (même pas besoin de mail, on trouve les messages sur la plateforme, + nos réseaux sociaux)

**Comment by AdrKacz** [comment]
Plus d'actualité
