### ISSUE TITLE
🌟 Back Swipe

### ISSUE THREAD

**Issue by mbeaufre** [AdrKacz/super-duper-guacamole#172]
# Is your feature request related to a problem? Please describe
Develop the ability to go back in the previous group (missclick/miss-swipe)

# Describe the solution you'd like
The ability to go back in the group. Ideally when the 'swipe' will be implemented, the swipe backwards would be to go back in a group.

# Describe alternatives you've considered
None.

# Additional context
None.

**Comment by AdrKacz** [comment]
À voir si la feature est intéressante, pas sur la *roadmap* pour le moment, on pourra en discuter la prochaine fois
