### ISSUE TITLE
🌟 Pseudo

### ISSUE THREAD

**Issue by mbeaufre** [AdrKacz/super-duper-guacamole#173]
# Is your feature request related to a problem? Please describe
The inability to have a personal name.

# Describe the solution you'd like
A customisable name, linked to the user. No need for uniqueness I think.

# Describe alternatives you've considered
None

# Additional context
None

**Comment by AdrKacz** [comment]
Duplicate of #122

**Comment by AdrKacz** [comment]
Pour ce qui est 'avoir juste un nom, il faut mettre un place un système évitant les noms non approprié *(connotation sexuelle, religieuse, ou autre pouvant mettre mal à l'aise un autre utilisateur)*

Je vois deux options:
1. Vérifier chaque noms à la main
2. Créer un système de vérification intern, un peu comme fonctionne actuellement le ban

La même question se pose pour une photo de profil, une description, et autre, c'est pour ça j'ai mis en *Duplicate* ☺️

**Comment by AdrKacz** [comment]
(J'ai changé le statut de la fermeture, le *check violet* c'est quand c'est résolu, c'est pas le cas ici ☺️ Le *barre grise* c'est quand cette issue ne vas pas être résolu *(duplicate, erreur non reproductible, pas dans les objectifs)*

Ici c'est *duplicate*, j'ai fermé pour qu'on centralise la discussion sur le même fil 👍 (sinon ça va vite devenir compliqué de tout suivre si chaque petit ajustement devient une nouvelle issue)
