### ISSUE TITLE
🧐 Nouvelles questions

### ISSUE THREAD

**Issue by AliceETRX** [AdrKacz/super-duper-guacamole#204]
On a besoin de questions plus pertinentes pour mettre ensemble nos utilisateurs dans less bons groups. Qui plus est, certains utilisateurs nous ont dit qu'ils ne se reconnaissaient dans aucune des réponses proposées.

Quelles questions mettre ? Comment améliorer ce système pour le rendre à la fois pertinent pour nous et pour l'utilisateur ?

Idées :
- Garder ce même système de 4 questions identiques pour tous et les changer de temps en temps en envoyant une notification disant que de nouvelles questions sont dispos -> peut potentiellement relancer les gens au passage
- Faire un système de questions en où selon la réponse, une autre question arrive -> potentiellement plus précis mais demande plus de travail et est-ce vraiment pertinent ?

**Comment by AliceETRX** [comment]
Ce qui en ressort de notre réunion : faire pour le moment une seule question 
"pourquoi es-tu là?"
réponse 1: faire la fête ce soir
réponse 2: trouver des potes pour faire un truc dans la semaine
réponse 3 : chatter

Peut-être : A long terme, lorsqu'il y aura plus d'utilisateurs: pouvoir faire une arbre de questions afin de mettre les gens qui veulent la même choses ensemble -> plus précis

**Comment by AdrKacz** [comment]
Questions supprimé de l'interface tant que nous n'avons pas d'utilisateurs authentifié, je ferme car le component dont il est question ne fais plus parti de l'application. Si le problème se pose toujours une fois qu'on pourra créer son profil et entrer ses préférences on ouvrira une nouvelle issue
