### ISSUE TITLE
🌟 Improve flow in questions

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/super-duper-guacamole#209]
# Is your feature request related to a problem? Please describe
- Le bouton "Je valide" ne sers pas à grand chose 
- On ne peut pas faire marche arrière
- On peut revenir à la page de *chat*, cela coupe les questions sans qu'on avertisse l'utilisateur qu'elles ont bien été enregistré
  - comment revenir à la page principale sans le bouton "je confirme" (*swipe vers la droite*) n'est pas très claire

# Describe the solution you'd like
L'expérience pour répondre aux questions doit être pus agréable et moins frustrante (possibilité de changer de réponses, revenir sur ses choix, savoir quand les choses sont enregistrés, pas de questions inutiles)

# Describe alternatives you've considered
À noter: le bouton "je confirme", même s'il ne fait *techniquement* rien, permet d'assurer l'utilisateur que tout est bien sauvegardé (même si c'est déjà le cas), il n'est cependant surement pas très utile 🤔

**Comment by AdrKacz** [comment]
# Ideas

- Pouvoir faire *marche avant / marche arrière* dans les questions (pour l'instant, si on veut **re**-sélectionner la même questions il faut cliquer pour *désélectionner* puis quitter puis re-cliquer .. l'enfer)
- Après avoir répondu aux questions, on peut proposer à l'utilisateur de directement changer de groupe

**Comment by mbeaufre** [comment]
Si tu veux je peux essayer de réfléchir à l'UX pour comment améliorer ça et te/vous proposer qqch ensuite?
Les questions ça me semble assez intuitif le déroulement, mais c'est vrai que si la personne ne souhaite pas répondre elle peut être un peu perdue.

**Comment by AdrKacz** [comment]
Les questions n'existe plus pour le moment et seront re-réfléchis lors de l'ajout d'utilisateur authentifié, je ferme donc l'issue car le component dont il est question n'existe plus
