### ISSUE TITLE
🐛 Error screen load forever

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/super-duper-guacamole#224]
# Describe the bug
En cas d'erreur *(quand tu es banni par exemple)* tu es redirigé sur le `error screen`, cependant, ensuite si tu clique sur la petite flèche qui tourne pour te reconnecter, soit il arrive a se reconnecter (et la plus d'erreur), soit l'écran est flou jusqu'à l'infini (ce qui n'est en soit pas illogique, c'est juste super frustrant, on a envie de spammer le bouton re-connexion mais on peut pas parce que tout est *blur*)

# Expected behavior
Aucune idée, à discuter de comment gérer les erreurs et les faites comprendre (pour avoir une tentative de re-connexion non frustrante)

**Comment by kiwily** [comment]
retour a un "écran d'accueil" avec un bouton "trouver un groupe" ?

**Comment by AdrKacz** [comment]
Plus d'error screen, je ne vois donc plus d'erreur qui s'y apparente, je ferme la tâche. On ouvrira une nouvelle au besoin.
