### ISSUE TITLE
🌟 Re-Change Group on new preferences

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/super-duper-guacamole#238]
# Is your feature request related to a problem? Please describe
Quand tu changes tes préférences, celles ci sont prises en compte seulement pour ton prochain changement de groupe.

# Describe the solution you'd like
Idéalement, il faudrait pouvoir changer de groupe à chaque fois que tu changes tes préférences.

# Additional context
Le problème c'est que on permettrait aux utilisateurs de changer de groupe pendant qu'ils sont déjà entrain de changer de groupe. Il faut faire attention que ça ne "ferme" pas un groupe pas encore ouvert (et donc qu'un utilisateur se trouve en attente forever)

**Comment by AliceETRX** [comment]
Tu veux dire que si tu changes tes préférences, Awa te change automatiquement de groupe sans demander ton avis ?

Je pense qu'au contraire, que les préférences soit prises en compte **que** lorsque tu changes de groupe c'est très bien, sinon tu risques de couper quelqu'un en pleine conversation... 

A la limite, l'utilisateur pourrait changer ses préférences puis, recevoir un message pop up lui proposant de changer de groupe pour que celles ci soient prises en compte, mais le faire sans son "accord", bof...

**Comment by AdrKacz** [comment]
Duplicate of #321 

L'idée de changer automatiquement de groupe est a faire rentrer en compte même si ca parait pas evident. En tout cas il n'est pas clair **quand** se changement de préférences prends effet.
