### ISSUE TITLE
🐛 I am notified to my messages

### ISSUE THREAD

**Issue by kiwily** [AdrKacz/super-duper-guacamole#249]
# Describe the bug
You can receive notifications from your own messages

# To Reproduce
1. be in a group and send a message
2. quickly press the home button of your phone
3. You're notified of a new message : yours

# Expected behavior
I shouldn't be notified of my messages

# Smartphone (please complete the following information)
 - Device: iPhoneSE

**Comment by AdrKacz** [comment]
Done.
See Update app to use HTTP API (https://github.com/AdrKacz/super-duper-guacamole/pull/304)
https://github.com/AdrKacz/super-duper-guacamole/blame/main/chat-backend/http/post/text-message/app.js#L61
