### ISSUE TITLE
🙋 Stop deactivating user (need help)

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/super-duper-guacamole#267]
# Stop deactivating user?
After 2 days of inactivity, we remove a user from the app, is this is good idea?

We can either remove or modify this behaviour.

**Comment by kiwily** [comment]
You just have to make sure that the user doesn't see the welcome messages, privacy policies and questions again the next time he connects (this should get stored on the app). It has to bee a seemless experience from the user point of view, what happens in the backend isn't important to the user.

**Comment by AdrKacz** [comment]
User never removed, that has been changed. Resolved as not relevant anymore
